export { default as FeedBack } from './Forms/FeedBack';
export { default as Icons } from './Svg/Icons';
export { default as Header } from './Header/Header';
export { default as Section } from './Sections/Section';
export { default as Deviders } from './Sections/Deviders';
export { default as Head } from './Head/Head';
export { default as Footer } from './Footer/Footer';
export { default as Preloader } from './Preloader/Preloader';
export { default as Social } from './Social/Social';
export { default as FullPage } from './Sections/FullPage';
export { default as Logo } from './Svg/Logo'