export { default as Layout } from './Layout';
export { default as AddProduct } from './AddProduct';
export { default as Product } from './Product';
export { default as Options } from './Options';
export { default as Navigation } from './Navigation';
export { default as InputPrice } from './InputPrice';
export { default as Settings } from './Settings';
export { default as AddDesc } from './AddDesc';
export { default as InputSwitch } from './InputSwitch';
